export default {
  stamps: [
    {
      id: "rfphskcb3",
      name: "index.html",
      code:
        '<html>\n  <head>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/p5.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.dom.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.sound.min.js"></script>\n    <link rel="stylesheet" type="text/css" href="style.css">\n  </head>\n  <body>\n    <script src=\'sketch.js\'></script>\n  </body>\n</html>\n',
      args: " ",
      x: 1551.2140684066003,
      y: 526.1806151153287,
      editorWidth: 225,
      editorHeight: 176.29205282888586,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: true,
      isTxtFile: false,
      isMediaFile: false,
      hidden: true,
      exported: true,
      zIndex: -1,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/layout.8a437d55.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "e6gmt31vd",
      name: "style.css",
      code: "html, body {\n  margin: 0;\n  padding: 0;\n}",
      args: " ",
      x: 1551.6900090741035,
      y: 889.4753177293393,
      editorWidth: 225,
      editorHeight: 175,
      iframeWidth: 0,
      iframeHeight: 0,
      isIndex: false,
      isTxtFile: true,
      isMediaFile: false,
      hidden: true,
      exported: true,
      zIndex: -1,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/file.5bd43cb8.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "k6jqu86o0",
      name: "setup",
      code: "createCanvas(200, 200)",
      args: "",
      x: 760,
      y: 420,
      editorWidth: 260,
      editorHeight: 200,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 682,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/tool.d68b9b61.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "ipvqwxobk",
      name: "draw",
      code: "background(220)",
      args: "",
      x: 1280,
      y: 420,
      editorWidth: 260,
      editorHeight: 200,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 681,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/tool.d68b9b61.svg",
      lineHighLightingStatus: "none"
    }
  ],
  scale: 1,
  originX: -521.5432232678384,
  originY: -319.6558852454648,
  worldKey: "starter",
  worldEdited: true,
  snapToGrid: false,
  linesOn: false,
  js:
    "function setup(){\n  createCanvas(200, 200)\n}\n\nfunction draw(){\n  background(220)\n}\n",
  highlightedLines: {}
};
