export default {
	stamps: [
		{
			id: "rfphskcb3",
			name: "index.html",
			code:
				'<html>\n  <head>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/p5.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.dom.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.sound.min.js"></script>\n    <link rel="stylesheet" type="text/css" href="style.css">\n  </head>\n  <body>\n    <script src=\'sketch.js\'></script>\n  </body>\n</html>\n',
			args: " ",
			x: 1551.2140684066003,
			y: 526.1806151153287,
			editorWidth: 225,
			editorHeight: 176.29205282888586,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: true,
			isTxtFile: false,
			isMediaFile: false,
			hidden: true,
			exported: true,
			zIndex: -1,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/layout.8a437d55.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "e6gmt31vd",
			name: "style.css",
			code: "html, body {\n  margin: 0;\n  padding: 0;\n}",
			args: " ",
			x: 1551.6900090741035,
			y: 889.4753177293393,
			editorWidth: 225,
			editorHeight: 175,
			iframeWidth: 0,
			iframeHeight: 0,
			isIndex: false,
			isTxtFile: true,
			isMediaFile: false,
			hidden: true,
			exported: true,
			zIndex: -1,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/file.5bd43cb8.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "u7d8r8zg7",
			name: "setup",
			code: "createCanvas(200,200)",
			args: "",
			x: -220,
			y: 1340,
			editorWidth: 163.77673952969928,
			editorHeight: 45.91477877712373,
			iframeWidth: 60,
			iframeHeight: 60,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: true,
			exported: true,
			zIndex: 828,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/tool.d68b9b61.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "io132adyu",
			name: "// different 'p...",
			code: "// different 'painting tools'",
			args: " ",
			x: -220,
			y: 1540,
			editorWidth: 538,
			editorHeight: 40,
			iframeWidth: 0,
			iframeHeight: 0,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 849,
			isBlob: true,
			codeSize: 28,
			icon: "./static/media/globe.50d70b6d.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "z63p5s1jd",
			name: "lineTool",
			code:
				"// draw a line\nstroke(200);\nstrokeWeight(1)\nline(x, y, lastX, lastY)\n  ",
			args: "x=50, y=50, lastX = 0, lastY = 0",
			x: -220,
			y: 1700,
			editorWidth: 278,
			editorHeight: 200,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 854,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/box.310d8273.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "4qr4vn2xt",
			name: "circleTool",
			code:
				"// generate a random size\nvar size = random(0, 20)\n\n// set the opacity\nvar opacity = map(size, 0, 20, 0, 255)\n\n// draw a circle   \nfill(200, opacity)\nnoStroke()\nellipse(x,y,size, size)",
			args: "x=50, y=50",
			x: 340,
			y: 1700,
			editorWidth: 278,
			editorHeight: 199.99999999999994,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 855,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/box.310d8273.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "dmjucllic",
			name: "rectTool",
			code:
				"// generate a random size\nvar size = random(0, 20)\n\n// set the opacity\nvar opacity = map(size, 0, 20, 0, 255)\n\n// draw a rectangle\nrectMode(CENTER)\nfill(200, opacity)\nnoStroke()\nrect(x,y,size, size)",
			args: "x=50, y=50",
			x: 900,
			y: 1700,
			editorWidth: 278,
			editorHeight: 199.99999999999994,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 856,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/box.310d8273.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "pkjccf076",
			name: "// pass a tool ...",
			code:
				"// pass a tool function in as a parameter to 'paint' with that shape",
			args: " ",
			x: -220,
			y: 2100,
			editorWidth: 1158,
			editorHeight: 40,
			iframeWidth: 0,
			iframeHeight: 0,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 857,
			isBlob: true,
			codeSize: 28,
			icon: "./static/media/globe.50d70b6d.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "8as41qoym",
			name: "painter",
			code:
				"// made a fading background\ncolorMode(RGB, 255, 255, 255, 1);\nbackground(0, 0, 0, .01);\n\n// darw using the mouse position\npaintingFn(mouseX, mouseY, pmouseX, pmouseY)\n",
			args: "paintingFn = lineTool",
			x: -220,
			y: 2260,
			editorWidth: 318,
			editorHeight: 200.00000000000006,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 845,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/bell.86facacc.svg",
			lineHighLightingStatus: "none"
		},
		{
			id: "xqccowqfy",
			name: "draw",
			code:
				"// try drawing with different tools\n\n//painter(lineTool)\npainter(circleTool)\n// painter(rectTool)",
			args: "",
			x: 380,
			y: 2260,
			editorWidth: 260,
			editorHeight: 200.00000000000006,
			iframeWidth: 200,
			iframeHeight: 200,
			isIndex: false,
			isTxtFile: false,
			isMediaFile: false,
			hidden: false,
			exported: true,
			zIndex: 858,
			isBlob: false,
			codeSize: 14,
			icon: "./static/media/box.310d8273.svg",
			lineHighLightingStatus: "none"
		}
	],
	scale: 0.6319816978275787,
	originX: 365.1261833964586,
	originY: -892.0169454279676,
	worldKey: "passing_functions~maayan",
	worldEdited: true,
	worldPublishTime:
		"Mon Feb 17 2020 02:14:58 GMT-0800 (Pacific Standard Time)",
	snapToGrid: false,
	linesOn: false,
	js:
		"function setup(){\n  createCanvas(200,200)\n}\n\n\n// different 'painting tools'\n\n\nfunction lineTool(x=50, y=50, lastX = 0, lastY = 0){\n  // draw a line\n  stroke(200);\n  strokeWeight(1)\n  line(x, y, lastX, lastY)\n    \n}\n\nfunction circleTool(x=50, y=50){\n  // generate a random size\n  var size = random(0, 20)\n  \n  // set the opacity\n  var opacity = map(size, 0, 20, 0, 255)\n  \n  // draw a circle   \n  fill(200, opacity)\n  noStroke()\n  ellipse(x,y,size, size)\n}\n\nfunction rectTool(x=50, y=50){\n  // generate a random size\n  var size = random(0, 20)\n  \n  // set the opacity\n  var opacity = map(size, 0, 20, 0, 255)\n  \n  // draw a rectangle\n  rectMode(CENTER)\n  fill(200, opacity)\n  noStroke()\n  rect(x,y,size, size)\n}\n\n\n// pass a tool function in as a parameter to 'paint' with that shape\n\n\nfunction painter(paintingFn = lineTool){\n  // made a fading background\n  colorMode(RGB, 255, 255, 255, 1);\n  background(0, 0, 0, .01);\n  \n  // darw using the mouse position\n  paintingFn(mouseX, mouseY, pmouseX, pmouseY)\n  \n}\n\nfunction draw(){\n  // try drawing with tools\n  \n  //painter(lineTool)\n  painter(circleTool)\n  // painter(rectTool)\n}\n",
	highlightedLines: {}
};
