export default {
  stamps: [
    {
      id: "rfphskcb3",
      name: "index.html",
      code:
        '<html>\n  <head>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/p5.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.dom.min.js"></script>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.sound.min.js"></script>\n    <link rel="stylesheet" type="text/css" href="style.css">\n  </head>\n  <body>\n    <script src=\'sketch.js\'></script>\n  </body>\n</html>\n',
      args: " ",
      x: 1551.2140684066003,
      y: 526.1806151153287,
      editorWidth: 225,
      editorHeight: 176.29205282888586,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: true,
      isTxtFile: false,
      isMediaFile: false,
      hidden: true,
      exported: true,
      zIndex: -1,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/layout.8a437d55.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "e6gmt31vd",
      name: "style.css",
      code: "html, body {\n  margin: 0;\n  padding: 0;\n}",
      args: " ",
      x: 1551.6900090741035,
      y: 889.4753177293393,
      editorWidth: 225,
      editorHeight: 175,
      iframeWidth: 0,
      iframeHeight: 0,
      isIndex: false,
      isTxtFile: true,
      isMediaFile: false,
      hidden: true,
      exported: true,
      zIndex: -1,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/file.5bd43cb8.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "7jqn88erd",
      name: "// basic setup",
      code: "// basic setup",
      args: " ",
      x: 760,
      y: 280,
      editorWidth: 698,
      editorHeight: 40,
      iframeWidth: 0,
      iframeHeight: 0,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 684,
      isBlob: true,
      codeSize: 28,
      icon: "/static/media/globe.50d70b6d.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "0psoiyaga",
      name: "var xPos = 0",
      code: "var xPos = 0\nvar maxSize = 20",
      args: " ",
      x: 760,
      y: 420,
      editorWidth: 120.72506930849877,
      editorHeight: 160.00000000000003,
      iframeWidth: 0,
      iframeHeight: 0,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 663,
      isBlob: true,
      codeSize: 14,
      icon: "/static/media/globe.50d70b6d.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "cjkdv45i9",
      name: "setup",
      code: "createCanvas(200, 200)\nbackground(175, 112, 248)\nnoStroke()",
      args: "",
      x: 940,
      y: 420,
      editorWidth: 258.0000000000001,
      editorHeight: 79.99999999999997,
      iframeWidth: 80,
      iframeHeight: 80,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 671,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/tool.d68b9b61.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "6knpj1zdw",
      name: "// drawing a pa...",
      code: "// drawing a pattern with the helper 'sizeDot'",
      args: " ",
      x: 760,
      y: 700,
      editorWidth: 718.1478969040777,
      editorHeight: 40,
      iframeWidth: 0,
      iframeHeight: 0,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 680,
      isBlob: true,
      codeSize: 28,
      icon: "/static/media/globe.50d70b6d.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "k6jqu86o0",
      name: "sizeDot",
      code:
        "// generate a random size\nvar size = random(0, maxSize)\n\n// set the opacity\nvar opacity = map(size, 0, maxSize, 0, 255)\n\n// draw a dot   \nfill(255, opacity)\nellipse(x,y,size, size)",
      args: "x=mouseX, y=mouseY",
      x: 760,
      y: 840,
      editorWidth: 318,
      editorHeight: 200,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 686,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/box.310d8273.svg",
      lineHighLightingStatus: "none"
    },
    {
      id: "ipvqwxobk",
      name: "draw",
      code:
        "// update xPos and background\nbackground(175, 112, 248, 10)\nxPos = (xPos +2) % width\n\n// draw a row of dots\nfor(var i = 0; i < height/maxSize; i++){\n  sizeDot(xPos, i*maxSize )\n}",
      args: "",
      x: 1340,
      y: 840,
      editorWidth: 297.9999999999998,
      editorHeight: 200,
      iframeWidth: 200,
      iframeHeight: 200,
      isIndex: false,
      isTxtFile: false,
      isMediaFile: false,
      hidden: false,
      exported: true,
      zIndex: 687,
      isBlob: false,
      codeSize: 14,
      icon: "/static/media/tool.d68b9b61.svg",
      lineHighLightingStatus: "none"
    }
  ],
  scale: 0.7714158336818215,
  originX: -353.2590405369888,
  originY: -127.37562184791057,
  worldKey: "starter",
  worldEdited: true,
  snapToGrid: false,
  linesOn: false,
  js:
    "\n// basic setup\n\n\n\nvar xPos = 0\nvar maxSize = 20\n\n\nfunction setup(){\n  createCanvas(200, 200)\n  background(175, 112, 248)\n  noStroke()\n}\n\n\n// drawing a pattern with the helper 'sizeDot'\n\n\nfunction sizeDot(x=mouseX, y=mouseY){\n  // generate a random size\n  var size = random(0, maxSize)\n  \n  // set the opacity\n  var opacity = map(size, 0, maxSize, 0, 255)\n  \n  // draw a dot   \n  fill(255, opacity)\n  ellipse(x,y,size, size)\n}\n\nfunction draw(){\n  // update xPos and background\n  background(175, 112, 248, 10)\n  xPos = (xPos +2) % width\n  \n  // draw a row of dots\n  for(var i = 0; i < height/maxSize; i++){\n    sizeDot(xPos, i*maxSize )\n  }\n}\n",
  highlightedLines: {}
};
